### ISSUE TITLE
setState warning

### ISSUE THREAD

**Issue by qur2** [jwoudenberg/flyd-lift-react#2] opened 2015-11-17 08:41 UTC
Hi,

I'm using your library in a case that is a bit different than what I see in the tests: I have a higher component that builds subcomponents and injects streams into them. This means that the lifting happens inside in a `render()` call.
The problem is that while lifting a component, `.setState()` is called and React emits a warning because the state is mutated during a render cycle. Of course, it's only a warning, but it would be nice to get rid of it.
So far, the fix I found is to wrap the `.setState()` call in a function that checks that the new state is different from the component state. In order to do that, I use `ramda.equals()` which has the benefit to delegate to `state.equals` if there is any (and thus benefits from fast comparison with immutablejs for example). The drawback, obviously, is that the library would have ramda as a dependency. I find it acceptable since flyd already depends on it.

What do you think? Would a PR be welcome?

**Comment by stoeffel** [comment] 2015-11-24 09:45
Could you provide the code of your HoC? I think there should be a possibility to lift the subcomponents outside of `render`. This would be cleaner IMO, than comparing the state.

**Comment by qur2** [comment] 2015-11-26 08:20
Here you go, it's basically the same thing as you wrote, using {{ramda}} and with the equality check before setting state:

``` js
import R from 'ramda';
import flyd from 'flyd';
import React from 'react';


const onStreamSetState = component => (state) => {
  if (!R.equals(component.state, state)) component.setState(state);
};

export default function Lift(Component) {
  const componentDisplayName =
    Component.name ||
    Component.displayName ||
    'Component';

  const ComposedComponent = class extends React.Component {
    constructor(props, context) {
      super(props, context);
      const propsStream = this.propsStream = mergePropertyStreams(props);
      this.state = propsStream();
      this.activeStream = false;
    }

    componentWillMount() {
      this.stateStream = flyd.map(onStreamSetState(this), this.propsStream);
    }

    componentWillReceiveProps(nextProps) {
      this.stateStream.end(true);
      this.propsStream.end(true);
      this.propsStream = mergePropertyStreams(nextProps);
      this.stateStream = flyd.map(onStreamSetState(this), this.propsStream);
    }

    componentWillUnmount() {
      var f = flyd
      this.stateStream.end(true);
      this.propsStream.end(true);
    }

    render() {
      return <Component {...this.state} />;
    }
  };

  ComposedComponent.displayName = 'Lifted' + componentDisplayName;

  return ComposedComponent;
}

const reify = ([name, stream]) => [name, stream()];
const collectStreams = R.pluck(1);

//Takes an object of streams and returns a stream of objects.
function mergePropertyStreams (map) {
  const pairs = R.toPairs(map);
  const [streams, others] = R.reduce(([s, o], pair) => {
    return flyd.isStream(pair[1]) ? [s.concat([pair]), o] : [s, o.concat([pair])];
  }, [[], []], pairs);
  const concatOthers = R.concat(others),
        composeProps = R.compose(R.fromPairs, concatOthers, R.map(reify));
  const unifiedStream = flyd.stream(collectStreams(streams), () => composeProps(streams));
  return flyd.immediate(unifiedStream);
}
```

**Comment by jwoudenberg** [comment] 2015-11-28 13:11
Hey there. Thanks for your issue and sorry for the late response, for some reason I just found out about this issue. Anyways, I think the core of the problem is that `flyd.on()` gets called synchronously with the initial value of the stream, which is a bit superfluous considering that's the value we've already set that value on the state in the `getInitialState()` method.

This is both the reason your solution works and the reason I think it's overkill ;). The way I see it, if we ignore that initial call to `flyd.on()`, we're done. You can still use do a `shouldComponentRender` check of course, but in my eyes that should be the responsibility of a separate HOC (one that I see no reason shouldn't play nice with this one).

I'll give this a look and report back here when I find a solution :).

**Comment by jwoudenberg** [comment] 2015-11-28 13:53
I played around with it and actually cannot confirm the behavior I described in my previous comment. So I'm at a loss to explain what is causing `setState` to be called early. Could you share the code using the `Lift` component?

**Comment by qur2** [comment] 2015-12-01 20:51
Hi,

I looked around, unfortunately, I don't have it anymore. I'm not quite done wrapping my mind around those concepts and for the sake of performing, I shied away to things I know better.

As far as I remember, when exporting a component, I would just wrap it: 

``` js
export default Lift(TheComponent)
```

Your explanation about the initial call to `.on` sounded convincing to me. I thought that it maybe comes from `flyd.immediate(unifiedStream)`

**Comment by jwoudenberg** [comment] 2015-12-02 19:51
It sounded convincing to me to, but sadly it didn't seem to correspond to reality ;). Anyway, because we seem to have some trouble reproducing it, I'll close this issue. Should you give it another try at some point and run into the same problem, I'd be happy to learn about it.

**Closed as completed** 2015-12-02 19:51 UTC
